#### Objective of this kernel:
* To implement svm machine learning algorithm
* To save our model 
* To  measure the accuracy of the model

## Importing our libraries 

In [49]:
import numpy as np

import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import matplotlib.pyplot as plt



# Input data files are available in the "../output/" directory.
import os

for dirname, _, filenames in os.walk('./output/'):
    
    for filename in filenames:
        
        print(os.path.join(dirname, filename))
        
# Any results you write to the current directory are saved as output.

./output/linearmodel.pickle
./output/naive_bayes.pickle
./output/KNNmodel.pickle
./output/processed_data.csv
./output/cleaned_data.csv
./output/Logregmodel.pickle
./output/SVMmodel.pickle
./output/.ipynb_checkpoints/cleaned_data-checkpoint.csv


## Reading the data set

In [50]:
df = pd.read_csv('./output/cleaned_data.csv')

df.shape

(238, 8)

## we are going to transform all our categorical data to proper format to be fed to our machine learning algorithms
* We preprocess our data with the LabelEncoder from sklearn

#### Preprocessing our independent variable x and dependent variable y

In [52]:
from sklearn.preprocessing import LabelEncoder

label_encoder_x=LabelEncoder()

#preprocessing x

Age=label_encoder_x.fit_transform(list(df["Age"]))

Gender=label_encoder_x.fit_transform(list(df["Gender"]))

wassce_grade=label_encoder_x.fit_transform(list(df["wassce grade"]))

level=label_encoder_x.fit_transform(list(df["level"]))

access_to_a_laptop_or_internet=label_encoder_x.fit_transform(list(df["access to a laptop or internet"]))

study_group=label_encoder_x.fit_transform(list(df["study group"]))

time_spent_on_independent_studies=label_encoder_x.fit_transform(list(df["time spent on independent studies"]))

current_CGPA=label_encoder_x.fit_transform(list(df["current CGPA"]))


x=list(zip(Age,Gender,wassce_grade,access_to_a_laptop_or_internet,study_group,time_spent_on_independent_studies,))
y=list(current_CGPA)

# Lets start implementing svm machine learning algorithm on our dataset

### Fitting the training data

# scale dataset

In [55]:
from sklearn.model_selection import train_test_split 

import pickle # This is used to save our model to be used in the future

# we split our data into training and testing dataset


from sklearn.preprocessing import StandardScaler # to scale our data 

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
from sklearn.preprocessing import StandardScaler # to scale our data 
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

### Initializing Support Neural Network and fitting the training data

In [58]:
import warnings
warnings.filterwarnings('ignore')
import sklearn

from sklearn.neural_network import MLPClassifier

from sklearn.neural_network import MLPRegressor


# Import necessary modules

from sklearn.model_selection import train_test_split

from sklearn.metrics import mean_squared_error

from math import sqrt

from sklearn.metrics import r2_score

from sklearn.neural_network import MLPClassifier

from sklearn.model_selection import GridSearchCV

param_grid = [
        {
            'activation' : ['identity', 'logistic', 'tanh', 'relu'],
            'solver' : ['lbfgs', 'sgd', 'adam'],
            'hidden_layer_sizes': [
             (1,),(2,),(3,),(4,),(5,),(6,),(7,),(8,),(9,),(10,),(11,), (12,),(13,),(14,),(15,),(16,),(17,),(18,),(19,),(20,),(21,)
             ]
        }
       ]
best = 0
mlp = MLPClassifier( max_iter=9900)

clf = GridSearchCV(mlp, param_grid, cv=2,scoring='accuracy')
clf.fit(x_train,y_train)
print("Best parameters set found on development set:")
print(clf.best_params_)
mlp.fit(x_train,y_train)
nural_score = mlp.score(x_test,y_test)

Best parameters set found on development set:
{'activation': 'logistic', 'hidden_layer_sizes': (1,), 'solver': 'adam'}


In [59]:
with open("./output/Nural_network.pickle","wb") as f:
            pickle.dump(mlp,f)
print(nural_score)

0.3541666666666667


### Predicting the classes for test set

In [60]:
y_pred = mlp.predict(x_test)
print ("Predicted Value:", y_pred)

Predicted Value: [2 2 1 2 2 3 2 3 1 3 4 4 2 2 2 2 3 3 2 3 1 3 2 1 3 1 4 3 3 2 2 2 2 3 2 2 3
 2 4 3 4 1 4 2 1 3 2 3]


In [61]:
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report
print("Accuracy of the Neural network: {}%".format(round(accuracy_score(y_test, y_pred)*100,2)))
print("\nConfusion of theNeural network:\n")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report of the Neural network:\n")
print(classification_report(y_test, y_pred))

Accuracy of the Neural network: 35.42%

Confusion of theNeural network:

[[1 4 2 0]
 [4 7 2 2]
 [2 6 7 2]
 [0 3 4 2]]

Classification Report of the Neural network:

              precision    recall  f1-score   support

           1       0.14      0.14      0.14         7
           2       0.35      0.47      0.40        15
           3       0.47      0.41      0.44        17
           4       0.33      0.22      0.27         9

    accuracy                           0.35        48
   macro avg       0.32      0.31      0.31        48
weighted avg       0.36      0.35      0.35        48



In [63]:
from sklearn.metrics import mean_squared_error,mean_squared_log_error,confusion_matrix
print("The mean_squared_error of the KNN is: {}".format(mean_squared_error(y_test, y_pred)))
print("mean_squared_log_error of the KNN is: {}".format(mean_squared_log_error(y_test, y_pred)))

The mean_squared_error of the KNN is: 1.2083333333333333
mean_squared_log_error of the KNN is: 0.11463724670286697


#### loading linear KNN model so we dont have to rerun our algorithm 

In [64]:
pickle_in = open("./output/Nural_network.pickle","rb")
regressor = pickle.load(pickle_in)